### ISSUE TITLE
DRAFT: When Schnorr Cross Sig Agg?

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#20]
# Description
### Relevant Links

# About the Speaker
### Social Links
Github 
Twitter
Website

# Talk Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by fjahr** [comment]
Maybe not just when but also how, at least that's a question that is a bit easier to answer :)

Normally, I would be happy to take this myself but I have a scheduling conflict and will most likely not be able to join this year. But I am happy to support someone who wants to present on this and https://cisaresearch.org should be helpful as well. I will also check if I know someone who is going and is interested in speaking on this.

**Comment by miketwenty1** [comment]
@fjahr not sure if you still have a scheduling conflict, but if would love to have you or someone you would recommend for this topic. Otherwise if we don't get a speaker for it, I think we may drop it.

**Comment by fjahr** [comment]
> @fjahr not sure if you still have a scheduling conflict, but if would love to have you or someone you would recommend for this topic. Otherwise if we don't get a speaker for it, I think we may drop it.

Unfortunately, it still looks like I won't be able to make it. I will ping a few people who might be interested but feel free to close it if nobody volunteers in the next couple of days.

**Comment by marathon-gary** [comment]
What pre-requisite knowledge is needed for this topic?

**Comment by iglesiasbrandon** [comment]
Hey, @marathon-gary, yes, that's the hope for this issue. Are you knowledgeable on this subject and interested in giving a presentation?

**Comment by marathon-gary** [comment]
> Hey, @marathon-gary, yes, that's the hope for this issue. Are you knowledgeable on this subject and interested in giving a presentation?

I'm not sure how two gauge my knowledge on the subject but I'm open to discussing with others and learning enough to give a presentation.
I recall hearing about debating CISA vs. adaptor signatures. I know that libsecp-zkp merged half-agg earlier this year but full agg has little to no progress made on it, assumedly due to the interactive nature, which would require wallet (etc.) devs to adopt it. But even if there were wallets that want to adopt it, there's not a formal spec for how it would be accomplished.

If @fjahr has time to sync on the subject, perhaps he can be a good gauge of my knowledge? If it is sufficient, I would be happy to give a presentation. There is plenty of prep time before conference date.

**Comment by fjahr** [comment]
> If @fjahr has time to sync on the subject, perhaps he can be a good gauge of my knowledge? If it is sufficient, I would be happy to give a presentation. There is plenty of prep time before conference date.

Have you studied https://cisaresearch.org/ already? I try to document everything there as well as I can so that should be a good starting point for you. The information there should be enough for a presentation (I hope) so maybe you can use it to get a basic idea of how you would like to present CISA. I am happy to fill in the gaps and answer your questions beyond that and I would be very interested in your feedback to the content at https://cisaresearch.org/ as well!

I have also given a [short, high level presentation on CISA at Olso Freedom Forum that was recorded](https://www.youtube.com/watch?v=RGdeleSqpIU&t=6s) and we had [a panel discussion at Bitcoin 2024 as well](https://www.youtube.com/watch?v=HvI7NPI_Pk0) so maybe these can give you additional pointers on how to approach the topic.

**Comment by marathon-gary** [comment]
> Have you studied https://cisaresearch.org/ already?

Not in depth but I did listen to all the pods listed there. I see that BTC2024 panel is new as of a few days ago so I'll give that a listen and find some time to sit down to give CISA Research a more thorough review.

Thank you for the insights. I will chime back in sometime next week.

@iglesiasbrandon Is there a preferred time length for a talk like this?

**Comment by marathon-gary** [comment]
@iglesiasbrandon Would a 30 min talk be appropriate? There's definitely enough for a full hour but I'm not sure how schedule/timing goes for these talks.

**Comment by marathon-gary** [comment]
What would an attendee learn from this talk?
- How signature aggregation works, technically speaking and with code
- Current status of CISA
- Pros/Cons of CISA

Given the technical nature of the conference, I'm hoping to focus most time/energy on the first bullet point and will briefly cover the second and third point.

@iglesiasbrandon What sort of time slot might I be working with so I can begin tailoring a presentation appropriately?

(learning repo: https://github.com/EthnTuttle/aggregate)

**Comment by average-gary** [comment]
Sorry folks, looking the next week and a half or so and I'm not confident I could deliver quality talk on the subject. I do hope to find some people to discuss with at TABConf.

**Comment by EllyPembroke** [comment]
hey @average-gary I'm only seeing a meshtastic builder day project. What's the issue number for the talk you or Shane wanted to give at next gen?
