### ISSUE TITLE
RGB

### ISSUE THREAD

**Issue by cryptoquick** [TABConf/6.tabconf.com#26]
# Description
### What is this talk about? Give us as many details as possible. 
RGB, client-side validation, single use seals, smart contracts
### What would an attendee learn from this talk?
How RGB works and why it might be useful
### Is there anything folks should read up on before they attend this talk?
https://petertodd.org/2017/scalable-single-use-seal-asset-transfer#single-use-seal-definition

### Relevant Links
https://rgb.tech
https://rgb.info

# About the Speaker
Ideally @dr-orlovsky would give this talk, but if not, @cryptoquick can.

### Social Links
Github
Twitter
Website

# Talk Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by dr-orlovsky** [comment]
I do not think there is a need to apply. If there is an interest in RGB, client-side validation etc, they would have no choice other than to ask me, as a creator of it to present it, or ask me who can do that.

If not interested - I do not give a flying fuck, will not beg: they are free to do what they want and ignore trends in bitcoin.

**Comment by miketwenty1** [comment]
@dr-orlovsky happy to have builders in the discussion. Sounds like you are open to presenting on this topic if it's selected. Thank you.

**Comment by dr-orlovsky** [comment]
@dr-orlovsky yes, LNP/BP Standards Association will be happy to present on RGB when we are asked. You can discuss details with @UkolovaOlga

**Comment by iglesiasbrandon** [comment]
Hey @dr-orlovsky, That's not how TABConf works, please be respectful of folks who submit issues. If you are interested and passionate about a topic, you can submit an issue, and it will be reviewed. You can take a look at our schedule from last year to get an idea of what TABConf programming is like. https://github.com/orgs/TABConf/projects/1

**Comment by iglesiasbrandon** [comment]
Hey @cryptoquick, can you add a bit more detail to your issue description and title so that attendees can get more details about what they will learn?! a very descriptive issue increases the chances of issues being accepted. Folks will also be able to ask questions before the conference on this issue. 

Also, thank you for submitting this issue; we are going to start accepting issues very soon.

**Comment by UkolovaOlga** [comment]
> Hey @dr-orlovsky, That's not how TABConf works, please be respectful of folks who submit issues. If you are interested and passionate about a topic, you can submit an issue, and it will be reviewed. You can take a look at our schedule from last year to get an idea of what TABConf programming is like. https://github.com/orgs/TABConf/projects/1

@dr-orlovsky is literally the guy who built RGB spending 5 past years on it. @cryptoquick had been contributing to building apps on top of RGB, so they both know each other and there is absolutely nothing disrespectful in the communication made by Maxim. It's actually fun how you disregard him and send him away 'to file Issues' rather than invite him to speak as you kindly do with Hunter. 

I was mentioned in the communication simply because I am handling the schedules, conferences and many other activities - it was simply made to help you, not to offend you.

Anyway, as by now the RGB ecosystem has grown and it would indeed be very beneficial to your audience to learn more about it, from the people that actually built it. We can cover technical aspects, business ones and many more, depending on your goal for this year. I don't find GitHub issues a good format to clarify the details, so I can offer to try email format or chat, to make the collaboration more fruitful. Otherwise I can easily spam the repo with a good dozen of topics and questions we can cover - I don't think you would like that :)
Having said that, I would appreciate it if you or someone from your team could ping me either at ukolova@lnp-bp.org or on Telegram using dr_ukolova. We are also opened for throwing side events and other things, but I would kindly ask your guidance there.

Thanks!

**Comment by iglesiasbrandon** [comment]
Hey @UkolovaOlga,  

I may not be communicating and explaining the TABConf process clearly. 

Anyone and everyone is welcome to submit an issue for a topic they are passionate and excited about. 

> It's actually fun how you disregard him and send him away 'to file Issues' rather than invite him to speak as you kindly do with Hunter.

I am not sending @dr-orlovsky away; he is also welcome to submit an issue for a talk or workshop he would like to give at TABConf. He can also tag team this talk with Hunter iff they would like. 

We are very different from most conferences, we do not invite specific people to speak at TABConf. Folks have to take the initiative if they are interested in doing so. I did not invite Hunter, he opened this issue and i thanked him for doing so. 

I do agree a talk or workshop about RGB would be interesting! I was happy to see Hunter submit the issue. 

In regards to communicating about potential issues for talks and workshops, you can open a Github issue for those items. We organize the conference in the open on this GitHub repo so this is the best place to discuss programming. We also add side events folks organize on this repo so feel free to add those as well. Our previous years GitHub repo has some really good examples you can reference.

**Comment by cryptoquick** [comment]
@iglesiasbrandon If @dr-orlovsky is able to, I would prefer him to give the presentation, because he's a very engaging and dynamic speaker. I can do my best to fill in if needed, but they're big shoes to fill.

As with anything, if you want it to happen, I would recommend doing what @UkolovaOlga says.

**Comment by iglesiasbrandon** [comment]
Hey @cryptoquick ok, is @dr-orlovsky coming to the conference?

**Comment by cryptoquick** [comment]
@iglesiasbrandon I haven't heard back about this yet... Were you able to chat, @UkolovaOlga @miketwenty1 ?

**Comment by dr-orlovsky** [comment]
We have discussed the situation during Baltic Honeybadger conference few days ago. Due to the conflict with Plan B Forum in Lugano we would not be able to come to TABConf this year. Thank you for proposing us and hope to come next year!

**Comment by cryptoquick** [comment]
Sadly I won't be able to attend because we have a major deadline working for Ducat Protocol that I'll need to meet at this time.

Closing this unless someone else would like to pick up the talk.
