### ISSUE TITLE
Coordinate L2 Sidechain 'Hello World'

### ISSUE THREAD

**Issue by russeree** [TABConf/6.tabconf.com#94]
# Description
### What is this workshop about? Provide as many details as possible.
This workshop is about creating a Hello World application using the Anduro - Coordinate Sidechain which is a federated L2 Bitcoin sidechain. This "hello world" would enable users to craft their own pegin transaction, receive CBTC, and pegout back to Testnet3(4).

### What would an attendee learn from this workshop?

- Coordinate RPC
- Bitcoin RPC
- Python
- Transaction Structure Bitcoin vs Coordinate
- Tradeoffs and security models.

### Is there anything attendees should read up on before they attend this talk?
Attendees should  be familiar with the idea of a federated sidechain using the coordinate whitepaper and/or liquid whitepaper. Both behave similarly at the highest level.  
### Is there anything attendees should set up before the workshop?
Python 3.12
### Relevant Links
[Anduro.io](https://anduro.io)
 
# Level of difficulty 
Intermediate, users will be expected to understand the basics of an RPC beforehand, and how to make REST calls.
 
# About the Speaker
### Social Links
Github 
[russeree](https://github.com/russeree)
Twitter
[Portland.HODL](https://x.com/portlandhodl)

# Workshop Details
### Length of workshop
45 mins
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by EdJulineAnduro** [comment]
The approval of this issue is critical for the success of TABConf, specifically for our workshop on creating a "Hello World" application using the Anduro - Coordinate Sidechain. This workshop is a cornerstone of our event as it introduces attendees to the Coordinate federated L2 Bitcoin sidechain, enabling them to understand and interact with key components such as crafting pegin transactions, receiving CBTC, and performing pegout operations back to Testnet3(4).

Attendees will gain hands-on experience with Coordinate RPC, Bitcoin RPC, Python programming, and the nuances of transaction structures between Bitcoin and Coordinate, including the associated tradeoffs and security models. This session is designed for those with an intermediate level of understanding, particularly those familiar with RPC basics and REST calls.

Given the workshop's focus, participants need to familiarize themselves with the concepts of federated sidechains through the Coordinate whitepaper.

The success of this workshop, and by extension, its contribution to the overall impact of TABConf, hinges on the approval of this issue.

**Comment by russeree** [comment]
https://github.com/russeree/TABConf6-Coordinate

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this workshop!

**Comment by russeree** [comment]
Yeah, sorry it didn't quite go as well as expected.
